"""
Bible books metadata for all 66 books.
Contains Korean name, abbreviation, English name, URL abbreviation, and chapter counts.
"""

BOOKS = {
    # 구약 (39권)
    "창": {"abbr": "창", "name": "창세기", "english_name": "Genesis", "url_abbr": "gen", "chapters": 50},
    "출": {"abbr": "출", "name": "출애굽기", "english_name": "Exodus", "url_abbr": "exo", "chapters": 40},
    "레": {"abbr": "레", "name": "레위기", "english_name": "Leviticus", "url_abbr": "lev", "chapters": 27},
    "민": {"abbr": "민", "name": "민수기", "english_name": "Numbers", "url_abbr": "num", "chapters": 36},
    "신": {"abbr": "신", "name": "신명기", "english_name": "Deuteronomy", "url_abbr": "deu", "chapters": 34},
    "수": {"abbr": "수", "name": "여호수아", "english_name": "Joshua", "url_abbr": "jos", "chapters": 24},
    "삿": {"abbr": "삿", "name": "사사기", "english_name": "Judges", "url_abbr": "jdg", "chapters": 21},
    "룻": {"abbr": "룻", "name": "룻기", "english_name": "Ruth", "url_abbr": "rut", "chapters": 4},
    "삼상": {"abbr": "삼상", "name": "사무엘상", "english_name": "1 Samuel", "url_abbr": "1sa", "chapters": 31},
    "삼하": {"abbr": "삼하", "name": "사무엘하", "english_name": "2 Samuel", "url_abbr": "2sa", "chapters": 24},
    "왕상": {"abbr": "왕상", "name": "열왕기상", "english_name": "1 Kings", "url_abbr": "1ki", "chapters": 22},
    "왕하": {"abbr": "왕하", "name": "열왕기하", "english_name": "2 Kings", "url_abbr": "2ki", "chapters": 25},
    "대상": {"abbr": "대상", "name": "역대상", "english_name": "1 Chronicles", "url_abbr": "1ch", "chapters": 29},
    "대하": {"abbr": "대하", "name": "역대하", "english_name": "2 Chronicles", "url_abbr": "2ch", "chapters": 36},
    "스": {"abbr": "스", "name": "에스라", "english_name": "Ezra", "url_abbr": "ezr", "chapters": 10},
    "느": {"abbr": "느", "name": "느헤미야", "english_name": "Nehemiah", "url_abbr": "neh", "chapters": 13},
    "에": {"abbr": "에", "name": "에스더", "english_name": "Esther", "url_abbr": "est", "chapters": 10},
    "욥": {"abbr": "욥", "name": "욥기", "english_name": "Job", "url_abbr": "job", "chapters": 42},
    "시": {"abbr": "시", "name": "시편", "english_name": "Psalms", "url_abbr": "psa", "chapters": 150},
    "잠": {"abbr": "잠", "name": "잠언", "english_name": "Proverbs", "url_abbr": "pro", "chapters": 31},
    "전": {"abbr": "전", "name": "전도서", "english_name": "Ecclesiastes", "url_abbr": "ecc", "chapters": 12},
    "아": {"abbr": "아", "name": "아가", "english_name": "Song of Songs", "url_abbr": "sng", "chapters": 8},
    "사": {"abbr": "사", "name": "이사야", "english_name": "Isaiah", "url_abbr": "isa", "chapters": 66},
    "렘": {"abbr": "렘", "name": "예레미야", "english_name": "Jeremiah", "url_abbr": "jer", "chapters": 52},
    "애": {"abbr": "애", "name": "예레미야애가", "english_name": "Lamentations", "url_abbr": "lam", "chapters": 5},
    "겔": {"abbr": "겔", "name": "에스겔", "english_name": "Ezekiel", "url_abbr": "ezk", "chapters": 48},
    "단": {"abbr": "단", "name": "단이엘", "english_name": "Daniel", "url_abbr": "dan", "chapters": 12},
    "호": {"abbr": "호", "name": "호세아", "english_name": "Hosea", "url_abbr": "hos", "chapters": 14},
    "욜": {"abbr": "욜", "name": "요엘", "english_name": "Joel", "url_abbr": "jol", "chapters": 3},
    "암": {"abbr": "암", "name": "아모스", "english_name": "Amos", "url_abbr": "amo", "chapters": 9},
    "옵": {"abbr": "옵", "name": "오바댜", "english_name": "Obadiah", "url_abbr": "oba", "chapters": 1},
    "욘": {"abbr": "욘", "name": "요나", "english_name": "Jonah", "url_abbr": "jon", "chapters": 4},
    "미": {"abbr": "미", "name": "미가", "english_name": "Micah", "url_abbr": "mic", "chapters": 7},
    "나": {"abbr": "나", "name": "나훔", "english_name": "Nahum", "url_abbr": "nam", "chapters": 3},
    "합": {"abbr": "합", "name": "하박국", "english_name": "Habakkuk", "url_abbr": "hab", "chapters": 3},
    "습": {"abbr": "습", "name": "스바냐", "english_name": "Zephaniah", "url_abbr": "zep", "chapters": 3},
    "학": {"abbr": "학", "name": "학개", "english_name": "Haggai", "url_abbr": "hag", "chapters": 2},
    "슥": {"abbr": "슥", "name": "스가랴", "english_name": "Zechariah", "url_abbr": "zec", "chapters": 14},
    "말": {"abbr": "말", "name": "말라기", "english_name": "Malachi", "url_abbr": "mal", "chapters": 4},

    # 신약 (27권)
    "마": {"abbr": "마", "name": "마태복음", "english_name": "Matthew", "url_abbr": "mat", "chapters": 28},
    "막": {"abbr": "막", "name": "마가복음", "english_name": "Mark", "url_abbr": "mrk", "chapters": 16},
    "누": {"abbr": "누", "name": "누가복음", "english_name": "Luke", "url_abbr": "luk", "chapters": 24},
    "요": {"abbr": "요", "name": "요한복음", "english_name": "John", "url_abbr": "jhn", "chapters": 21},
    "행": {"abbr": "행", "name": "사도행전", "english_name": "Acts", "url_abbr": "act", "chapters": 28},
    "롬": {"abbr": "롬", "name": "로마서", "english_name": "Romans", "url_abbr": "rom", "chapters": 16},
    "고전": {"abbr": "고전", "name": "고린도전서", "english_name": "1 Corinthians", "url_abbr": "1co", "chapters": 16},
    "고후": {"abbr": "고후", "name": "고린도후서", "english_name": "2 Corinthians", "url_abbr": "2co", "chapters": 13},
    "갈": {"abbr": "갈", "name": "갈라디아서", "english_name": "Galatians", "url_abbr": "gal", "chapters": 6},
    "엡": {"abbr": "엡", "name": "에베소서", "english_name": "Ephesians", "url_abbr": "eph", "chapters": 6},
    "빌": {"abbr": "빌", "name": "빌립보서", "english_name": "Philippians", "url_abbr": "php", "chapters": 4},
    "골": {"abbr": "골", "name": "골로새서", "english_name": "Colossians", "url_abbr": "col", "chapters": 4},
    "살전": {"abbr": "살전", "name": "데살로니가전서", "english_name": "1 Thessalonians", "url_abbr": "1th", "chapters": 5},
    "살후": {"abbr": "살후", "name": "데살로니가후서", "english_name": "2 Thessalonians", "url_abbr": "2th", "chapters": 3},
    "딤전": {"abbr": "딤전", "name": "디모데전서", "english_name": "1 Timothy", "url_abbr": "1ti", "chapters": 6},
    "딤후": {"abbr": "딤후", "name": "디모데후서", "english_name": "2 Timothy", "url_abbr": "2ti", "chapters": 4},
    "딛": {"abbr": "딛", "name": "디도서", "english_name": "Titus", "url_abbr": "tit", "chapters": 3},
    "몬": {"abbr": "몬", "name": "빌레몬서", "english_name": "Philemon", "url_abbr": "phm", "chapters": 1},
    "히": {"abbr": "히", "name": "히브리서", "english_name": "Hebrews", "url_abbr": "heb", "chapters": 13},
    "약": {"abbr": "약", "name": "야고보서", "english_name": "James", "url_abbr": "jas", "chapters": 5},
    "벧전": {"abbr": "벧전", "name": "베드로전서", "english_name": "1 Peter", "url_abbr": "1pe", "chapters": 5},
    "벧후": {"abbr": "벧후", "name": "베드로후서", "english_name": "2 Peter", "url_abbr": "2pe", "chapters": 3},
    "요일": {"abbr": "요일", "name": "요한일서", "english_name": "1 John", "url_abbr": "1jn", "chapters": 5},
    "요이": {"abbr": "요이", "name": "요한이서", "english_name": "2 John", "url_abbr": "2jn", "chapters": 1},
    "요삼": {"abbr": "요삼", "name": "요한삼서", "english_name": "3 John", "url_abbr": "3jn", "chapters": 1},
    "유": {"abbr": "유", "name": "유다서", "english_name": "Jude", "url_abbr": "jud", "chapters": 1},
    "계": {"abbr": "계", "name": "요한계시록", "english_name": "Revelation", "url_abbr": "rev", "chapters": 22},
}

BOOK_ORDER = [
    "창", "출", "레", "민", "신", "수", "삿", "룻", "삼상", "삼하", "왕상", "왕하", "대상", "대하", "스", "느", "에", "욥", "시", "잠",
    "전", "아", "사", "렘", "애", "겔", "단", "호", "욜", "암", "옵", "욘", "미", "나", "합", "습", "학", "슥", "말",
    "마", "막", "누", "요", "행", "롬", "고전", "고후", "갈", "엡", "빌", "골", "살전", "살후", "딤전", "딤후", "딛", "몬", "히", "약",
    "벧전", "벧후", "요일", "요이", "요삼", "유", "계"
]
